import{describe,expect,it}from'vitest';import{EntityWorld,DeterministicRng,FixedStepClock}from'../packages/core/src/index';import{sampleSdf,sphere,polygonizeSdf,simplifyByVertexClustering}from'../packages/assets/src/index';import{simulateWorldHistory,makeSectorRecipe,chooseHlod,speciesSuitability}from'../packages/world/src/index';import{solveTwoBoneIk,emotionToFace,WeaponRigState}from'../packages/animation/src/index';import{heroBudget,BudgetWatchdog}from'../packages/quality/src/index';
describe('RAVEN subsystem integration invariants',()=>{
 it('keeps entity component identity stable across removals',()=>{const w=new EntityWorld(),s=w.store<number>('value'),a=w.create(),b=w.create(),c=w.create();s.set(a,1);s.set(b,2);s.set(c,3);w.destroy(b);expect(s.get(a)).toBe(1);expect(s.get(c)).toBe(3);expect(s.size).toBe(2);});
 it('caps fixed simulation catch-up',()=>{const f=new FixedStepClock(10,3);let steps=0;const r=f.advance(200,()=>steps++);expect(steps).toBe(3);expect(r.droppedMs).toBeGreaterThan(0);});
 it('reconstructs deterministic sector recipes',()=>{expect(makeSectorRecipe({x:12,z:-7},12345)).toEqual(makeSectorRecipe({x:12,z:-7},12345));});
 it('turns causal history inputs into bounded world state',()=>{const h=simulateWorldHistory({seed:5,ageYears:22,rainfall:.9,occupationPressure:.5,conflictPressure:.4});for(const v of Object.values(h))expect(v).toBeGreaterThanOrEqual(0);for(const v of Object.values(h))expect(v).toBeLessThanOrEqual(1);});
 it('builds and reduces implicit geometry',()=>{const mesh=polygonizeSdf(sampleSdf(sphere(0,0,0,1),{min:[-1.2,-1.2,-1.2],max:[1.2,1.2,1.2],resolution:10}));const lod=simplifyByVertexClustering(mesh,.3);expect(mesh.indices.length).toBeGreaterThan(0);expect(lod.positions.length).toBeLessThanOrEqual(mesh.positions.length);});
 it('solves reachable two-bone contacts',()=>{const r=solveTwoBoneIk({root:[0,0,0],mid:[0,-1,0],tip:[0,-2,0],target:[.5,-1.5,0],pole:[0,0,1]});expect(r.reached).toBe(true);expect(Math.hypot(...r.tip)).toBeGreaterThan(1);});
 it('drives facial state from systemic emotion',()=>{const face=emotionToFace({focus:1,fear:0,pain:0,anger:0,fatigue:0,calm:0});expect(face.browFurrow).toBeGreaterThan(0);expect(face.squint).toBeGreaterThan(0);});
 it('keeps weapon mechanics stateful',()=>{const w=new WeaponRigState();w.insertMagazine(6);w.state.chambered=true;expect(w.fire()).toBe(true);expect(w.state.slide).toBe(1);w.cycle(true);expect(w.state.chambered).toBe(true);expect(w.state.magazineRounds).toBe(5);});
 it('protects hero assets with larger budgets',()=>{expect(heroBudget({heroClass:'held-weapon',projectedImportance:.1,distance:1}).geometryMultiplier).toBeGreaterThan(heroBudget({heroClass:'ordinary',projectedImportance:.1,distance:1}).geometryMultiplier);});
 it('detects hard safety ceiling pressure',()=>{const w=new BudgetWatchdog({maxDrawCalls:10,maxTriangles:100,maxDynamicLights:4,maxParticles:20,maxShadowCasters:4});expect(w.inspect({drawCalls:12,triangles:80,dynamicLights:2,particles:10,shadowCasters:2}).max).toBeGreaterThan(1);});
 it('keeps seeded RNG repeatable',()=>{const a=new DeterministicRng(99),b=new DeterministicRng(99);expect(Array.from({length:16},()=>a.nextU32())).toEqual(Array.from({length:16},()=>b.nextU32()));});
 it('uses ecology constraints instead of blind scattering',()=>{const species={id:'fern',moisture:[.5,1]as[number,number],soil:[.3,1]as[number,number],light:[0,.65]as[number,number],verticalAffinity:.1,disturbanceTolerance:.35};expect(speciesSuitability({moisture:.8,soil:.8,light:.3,vertical:.1,disturbance:.1},species)).toBeGreaterThan(speciesSuitability({moisture:.1,soil:.1,light:1,vertical:.9,disturbance:1},species));});
 it('selects higher geometric detail for important objects',()=>{expect(chooseHlod({projectedImportance:.3,hero:false,memoryPressure:0})).toBeLessThan(chooseHlod({projectedImportance:.003,hero:false,memoryPressure:0}));});
});
