import{describe,expect,it}from'vitest';
import{DynamicResolutionController,FrameGraph,PassBudgetController,resolveProductionQuality,practicalCascadeSplits,buildStabilizedCascades,buildLightTiles}from'../packages/renderer/src/index';
describe('production renderer policy invariants',()=>{
 it('orders frame graph dependencies and computes resource lifetimes',()=>{const graph=new FrameGraph().declare({name:'depth',kind:'texture',transient:true}).declare({name:'color',kind:'texture',transient:true}).declare({name:'backbuffer',kind:'external',transient:false});graph.add({name:'present',reads:['color'],writes:['backbuffer'],execute:()=>{}}).add({name:'shade',reads:['depth'],writes:['color'],execute:()=>{}}).add({name:'depth',reads:[],writes:['depth'],execute:()=>{}});const plan=graph.compilePlan();expect(plan.passes.map(p=>p.name)).toEqual(['depth','shade','present']);expect(plan.lifetimes.get('depth')?.producer).toBe('depth');expect(plan.lifetimes.get('depth')?.lastUse).toBe(1);expect(plan.lifetimes.get('color')?.lastUse).toBe(2);});
 it('rejects undeclared frame graph resources',()=>{const graph=new FrameGraph();expect(()=>graph.add({name:'bad',reads:['missing'],writes:[],execute:()=>{}})).toThrow(/undeclared resource/);});
 it('smooths dynamic resolution pressure instead of oscillating every frame',()=>{const d=new DynamicResolutionController(16.6667,.67,1,.2,2);for(let i=0;i<12;i++)d.update(28,25);expect(d.scale).toBeLessThan(1);const low=d.scale;for(let i=0;i<30;i++)d.update(8,7);expect(d.scale).toBeGreaterThan(low);expect(d.scale).toBeLessThanOrEqual(1);});
 it('degrades pass-local quality when a measured GPU budget is exceeded',()=>{const b=new PassBudgetController(1).register({name:'ssr',scale:1,maxMs:2,enabled:true,minScale:.35,degradationRate:.1});b.observe('ssr',4);expect(b.passes.get('ssr')?.scale).toBe(.9);expect(b.pressure()).toBe(2);});
 it('sheds reflections and volumetrics before protected contact detail',()=>{const q=resolveProductionQuality(.8);expect(q.reflectionScale).toBeLessThan(q.contactShadowScale);expect(q.volumetricScale).toBeLessThan(q.contactShadowScale);expect(q.contactShadowSteps).toBeGreaterThanOrEqual(5);});
 it('builds practical shadow splits with complete monotonic coverage',()=>{const s=practicalCascadeSplits(.1,140,4,.68);expect(s).toHaveLength(4);expect(s[0].near).toBe(.1);expect(s[3].far).toBe(140);for(let i=1;i<s.length;i++)expect(s[i].near).toBeCloseTo(s[i-1].far,8);});
 it('stabilizes finite cascade matrices from a valid camera matrix',()=>{const identity=new Float32Array(16);for(let i=0;i<4;i++)identity[i*5]=1;const c=buildStabilizedCascades(identity,.1,100,[.3,-1,.2],1024,3,.68,50);expect(c).toHaveLength(3);for(const x of c){expect(x.texelWorldSize).toBeGreaterThan(0);for(const n of x.matrix)expect(Number.isFinite(n)).toBe(true);}});
 it('bounds tiled light lists and reports overflow deterministically',()=>{const lights=Array.from({length:40},(_,index)=>({x:16,y:16,radius:32,depthMin:0,depthMax:1,index}));const a=buildLightTiles(32,32,16,lights,8),b=buildLightTiles(32,32,16,[...lights].reverse(),8);expect(a.tiles.every(t=>t.indices.length<=8)).toBe(true);expect(a.overflow).toBeGreaterThan(0);expect(a).toEqual(b);});
});
