import{ShaderProgram}from'./ShaderProgram';import{ravenPbrVertex,ravenPbrFragment}from'./PbrShaders';import type{DirectionalLightPacket,EnvironmentLightPacket,LocalLightPacket}from'./Lighting';import type{CascadeData}from'./ShadowCascades';import type{TiledLightBinding}from'./TiledLightGrid';
export interface PbrMaterialPacket{baseColor:[number,number,number];roughness:number;metalness:number;emissive?:[number,number,number];emissiveIntensity?:number;ambientOcclusion?:number;reactive?:number;}
export interface PbrDrawPacket{vao:WebGLVertexArrayObject;indexCount:number;indexType:number;model:Float32Array;material:PbrMaterialPacket;objectId?:number;previousModel?:Float32Array;castsShadow?:boolean;}
export interface PbrCameraPacket{viewProj:Float32Array;position:[number,number,number];near?:number;far?:number;previousViewProj?:Float32Array;cameraCut?:boolean;}
export interface ShadowLightingBinding{texture:WebGLTexture;cascades:readonly CascadeData[];bias:number;normalBias:number;}
export interface PbrLightingPacket{directional?:DirectionalLightPacket;environment?:EnvironmentLightPacket;localLights?:readonly LocalLightPacket[];shadow?:ShadowLightingBinding;tiled?:TiledLightBinding;screenSpaceAo?:WebGLTexture;contactShadow?:WebGLTexture;viewportSize?:[number,number];}
const DEFAULT_DIRECTIONAL:DirectionalLightPacket={direction:[.35,-1,.25],color:[1,.965,.89],intensity:2.2};const DEFAULT_ENV:EnvironmentLightPacket={skyColor:[.2,.24,.29],groundColor:[.035,.04,.045],intensity:.35};
export class PbrPass{readonly program:ShaderProgram;constructor(readonly gl:WebGL2RenderingContext){this.program=new ShaderProgram(gl,ravenPbrVertex,ravenPbrFragment);}draw(camera:PbrCameraPacket,draws:readonly PbrDrawPacket[],lighting:PbrLightingPacket={}):void{const g=this.gl,p=this.program,dir=lighting.directional??DEFAULT_DIRECTIONAL,env=lighting.environment??DEFAULT_ENV,tiled=lighting.tiled,locals=tiled?.lights??lighting.localLights??[];p.use();g.uniformMatrix4fv(p.uniform('uViewProj'),false,camera.viewProj);g.uniform3fv(p.uniform('uCameraPos'),camera.position);g.uniform3fv(p.uniform('uLightDir'),dir.direction);g.uniform3fv(p.uniform('uLightColor'),dir.color);g.uniform1f(p.uniform('uLightIntensity'),dir.intensity);g.uniform3fv(p.uniform('uSkyColor'),env.skyColor);g.uniform3fv(p.uniform('uGroundColor'),env.groundColor??[.03,.035,.04]);g.uniform1f(p.uniform('uEnvironmentIntensity'),env.intensity??1);this.bindScreenLighting(lighting);this.bindLocalLights(locals,tiled);this.bindShadows(lighting.shadow);for(const d of draws){g.bindVertexArray(d.vao);g.uniformMatrix4fv(p.uniform('uModel'),false,d.model);g.uniformMatrix3fv(p.uniform('uNormalMatrix'),false,normalMatrix(d.model));g.uniform3fv(p.uniform('uBaseColor'),d.material.baseColor);g.uniform1f(p.uniform('uRoughness'),d.material.roughness);g.uniform1f(p.uniform('uMetalness'),d.material.metalness);const e=d.material.emissive??[0,0,0],ei=d.material.emissiveIntensity??1;g.uniform3f(p.uniform('uEmissive'),e[0]*ei,e[1]*ei,e[2]*ei);g.uniform1f(p.uniform('uAmbientOcclusion'),d.material.ambientOcclusion??1);g.uniform1f(p.uniform('uReactive'),d.material.reactive??0);g.drawElements(g.TRIANGLES,d.indexCount,d.indexType,0);}g.bindVertexArray(null);}
 private bindScreenLighting(lighting:PbrLightingPacket):void{const g=this.gl,p=this.program,size=lighting.viewportSize??[1,1];g.uniform2f(p.uniform('uViewportSize'),Math.max(1,size[0]),Math.max(1,size[1]));g.uniform1i(p.uniform('uHasScreenAo'),lighting.screenSpaceAo?1:0);if(lighting.screenSpaceAo){g.activeTexture(g.TEXTURE3);g.bindTexture(g.TEXTURE_2D,lighting.screenSpaceAo);g.uniform1i(p.uniform('uScreenAo'),3);}g.uniform1i(p.uniform('uHasContactShadow'),lighting.contactShadow?1:0);if(lighting.contactShadow){g.activeTexture(g.TEXTURE4);g.bindTexture(g.TEXTURE_2D,lighting.contactShadow);g.uniform1i(p.uniform('uContactShadow'),4);}}
 private bindLocalLights(lights:readonly LocalLightPacket[],tiled?:TiledLightBinding):void{const g=this.gl,p=this.program,count=Math.min(64,lights.length),positions=new Float32Array(64*4),colors=new Float32Array(64*4);for(let i=0;i<count;i++){const l=lights[i],o=i*4;positions[o]=l.position[0];positions[o+1]=l.position[1];positions[o+2]=l.position[2];positions[o+3]=Math.max(.001,l.range);colors[o]=l.color[0];colors[o+1]=l.color[1];colors[o+2]=l.color[2];colors[o+3]=Math.max(0,l.intensity);}g.uniform1i(p.uniform('uLocalLightCount'),count);g.uniform4fv(p.uniform('uLocalPositionRange[0]'),positions);g.uniform4fv(p.uniform('uLocalColorIntensity[0]'),colors);g.uniform1i(p.uniform('uHasTiledLights'),tiled&&count>0?1:0);if(tiled&&count>0){g.activeTexture(g.TEXTURE5);g.bindTexture(g.TEXTURE_2D,tiled.countsTexture);g.uniform1i(p.uniform('uTileCounts'),5);g.activeTexture(g.TEXTURE6);g.bindTexture(g.TEXTURE_2D,tiled.indicesTexture);g.uniform1i(p.uniform('uTileIndices'),6);g.uniform1i(p.uniform('uTileSize'),tiled.tileSize);}}
 private bindShadows(shadow?:ShadowLightingBinding):void{const g=this.gl,p=this.program;if(!shadow||!shadow.cascades.length){g.uniform1i(p.uniform('uHasShadows'),0);g.uniform1i(p.uniform('uCascadeCount'),0);return;}const count=Math.min(4,shadow.cascades.length),matrices=new Float32Array(64),splits=new Float32Array(4);for(let i=0;i<count;i++){matrices.set(shadow.cascades[i].matrix,i*16);splits[i]=shadow.cascades[i].split.far;}for(let i=count;i<4;i++)splits[i]=splits[Math.max(0,count-1)];g.uniform1i(p.uniform('uHasShadows'),1);g.uniform1i(p.uniform('uCascadeCount'),count);g.uniformMatrix4fv(p.uniform('uShadowMatrices[0]'),false,matrices);g.uniform4fv(p.uniform('uCascadeSplits'),splits);g.uniform1f(p.uniform('uShadowBias'),shadow.bias);g.uniform1f(p.uniform('uShadowNormalBias'),shadow.normalBias);g.activeTexture(g.TEXTURE7);g.bindTexture(g.TEXTURE_2D_ARRAY,shadow.texture);g.uniform1i(p.uniform('uShadowMap'),7);}
 dispose():void{this.program.dispose();}}
function normalMatrix(m:Float32Array):Float32Array{const a00=m[0],a01=m[1],a02=m[2],a10=m[4],a11=m[5],a12=m[6],a20=m[8],a21=m[9],a22=m[10],b01=a22*a11-a12*a21,b11=-a22*a10+a12*a20,b21=a21*a10-a11*a20,det=a00*b01+a01*b11+a02*b21;if(Math.abs(det)<1e-8)return new Float32Array([1,0,0,0,1,0,0,0,1]);const id=1/det;return new Float32Array([b01*id,(-a22*a01+a02*a21)*id,(a12*a01-a02*a11)*id,b11*id,(a22*a00-a02*a20)*id,(-a12*a00+a02*a10)*id,b21*id,(-a21*a00+a01*a20)*id,(a11*a00-a01*a10)*id]);}
