import type{RendererCapabilities}from'./Capabilities';
export type SceneColorFormat='rgba16f'|'rgba8';
export class SceneTargets{
 color!:WebGLTexture;normalRoughness!:WebGLTexture;baseColorMetal!:WebGLTexture;depth!:WebGLTexture;framebuffer!:WebGLFramebuffer;width=0;height=0;colorFormat:SceneColorFormat='rgba8';hdr=false;
 constructor(readonly gl:WebGL2RenderingContext,readonly capabilities?:RendererCapabilities){}
 ensure(width:number,height:number):void{if(this.width===width&&this.height===height)return;this.dispose();if(width<1||height<1)throw new RangeError('Scene target dimensions must be positive');const g=this.gl,c=g.createTexture(),n=g.createTexture(),b=g.createTexture(),d=g.createTexture(),f=g.createFramebuffer();if(!c||!n||!b||!d||!f)throw new Error('Failed to allocate RAVEN scene targets');this.color=c;this.normalRoughness=n;this.baseColorMetal=b;this.depth=d;this.framebuffer=f;this.width=width;this.height=height;const wantsHdr=this.capabilities?.colorBufferFloat??!!g.getExtension('EXT_color_buffer_float');this.allocateColor(wantsHdr);this.allocateNormalRoughness(wantsHdr);this.allocateBaseColorMetal();this.allocateDepth();g.bindFramebuffer(g.FRAMEBUFFER,f);this.attach();let status=g.checkFramebufferStatus(g.FRAMEBUFFER);if(status!==g.FRAMEBUFFER_COMPLETE&&wantsHdr){this.allocateColor(false);this.allocateNormalRoughness(false);this.attach();status=g.checkFramebufferStatus(g.FRAMEBUFFER);}g.bindFramebuffer(g.FRAMEBUFFER,null);g.bindTexture(g.TEXTURE_2D,null);if(status!==g.FRAMEBUFFER_COMPLETE){this.dispose();throw new Error(`Incomplete scene framebuffer: 0x${status.toString(16)}`);}}
 private attach():void{const g=this.gl;g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,this.color,0);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT1,g.TEXTURE_2D,this.normalRoughness,0);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT2,g.TEXTURE_2D,this.baseColorMetal,0);g.framebufferTexture2D(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.TEXTURE_2D,this.depth,0);g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1,g.COLOR_ATTACHMENT2]);}
 private commonTextureParams(filter:number):void{const g=this.gl;g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,filter);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,filter);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);}
 private allocateColor(hdr:boolean):void{const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.color);const linear=!hdr||(this.capabilities?.floatLinearFiltering??!!g.getExtension('OES_texture_float_linear'));this.commonTextureParams(linear?g.LINEAR:g.NEAREST);if(hdr){g.texImage2D(g.TEXTURE_2D,0,g.RGBA16F,this.width,this.height,0,g.RGBA,g.HALF_FLOAT,null);this.colorFormat='rgba16f';this.hdr=true;}else{g.texImage2D(g.TEXTURE_2D,0,g.RGBA8,this.width,this.height,0,g.RGBA,g.UNSIGNED_BYTE,null);this.colorFormat='rgba8';this.hdr=false;}}
 private allocateNormalRoughness(hdr:boolean):void{const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.normalRoughness);const linear=!hdr||(this.capabilities?.floatLinearFiltering??!!g.getExtension('OES_texture_float_linear'));this.commonTextureParams(linear?g.LINEAR:g.NEAREST);if(hdr)g.texImage2D(g.TEXTURE_2D,0,g.RGBA16F,this.width,this.height,0,g.RGBA,g.HALF_FLOAT,null);else g.texImage2D(g.TEXTURE_2D,0,g.RGBA8,this.width,this.height,0,g.RGBA,g.UNSIGNED_BYTE,null);}
 private allocateBaseColorMetal():void{const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.baseColorMetal);this.commonTextureParams(g.LINEAR);g.texImage2D(g.TEXTURE_2D,0,g.RGBA8,this.width,this.height,0,g.RGBA,g.UNSIGNED_BYTE,null);}
 private allocateDepth():void{const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.depth);this.commonTextureParams(g.NEAREST);g.texImage2D(g.TEXTURE_2D,0,g.DEPTH_COMPONENT24,this.width,this.height,0,g.DEPTH_COMPONENT,g.UNSIGNED_INT,null);}
 dispose():void{for(const t of [this.color,this.normalRoughness,this.baseColorMetal,this.depth])if(t)this.gl.deleteTexture(t);if(this.framebuffer)this.gl.deleteFramebuffer(this.framebuffer);this.color=undefined as unknown as WebGLTexture;this.normalRoughness=undefined as unknown as WebGLTexture;this.baseColorMetal=undefined as unknown as WebGLTexture;this.depth=undefined as unknown as WebGLTexture;this.framebuffer=undefined as unknown as WebGLFramebuffer;this.width=this.height=0;this.colorFormat='rgba8';this.hdr=false;}
}
