import{FullscreenPass}from'./FullscreenPass';import type{RendererCapabilities}from'./Capabilities';import type{DepthPyramidLevel}from'./DepthPyramidPass';import type{PbrCameraPacket}from'./PbrPass';import{invertMat4}from'./ShadowCascades';
export interface ScreenSpaceReflectionSettings{enabled?:boolean;resolutionScale?:number;maxDistance?:number;thickness?:number;steps?:number;roughnessCutoff?:number;}
export interface ResolvedScreenSpaceReflectionSettings{enabled:boolean;resolutionScale:number;maxDistance:number;thickness:number;steps:number;roughnessCutoff:number;}
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function resolveScreenSpaceReflectionSettings(input:ScreenSpaceReflectionSettings={},qualityScale=1,budgetScale=1):ResolvedScreenSpaceReflectionSettings{return{enabled:input.enabled??true,resolutionScale:clamp((input.resolutionScale??.75)*qualityScale*budgetScale,.25,1),maxDistance:clamp(input.maxDistance??48,2,200),thickness:clamp(input.thickness??.12,.01,2),steps:Math.max(8,Math.min(64,Math.round((input.steps??40)*clamp(qualityScale,.25,1)))),roughnessCutoff:clamp(input.roughnessCutoff??.72,.1,.95)};}
const fs=`#version 300 es
precision highp float;
in vec2 vUv;out vec4 outReflection;
uniform sampler2D uColor;uniform sampler2D uDepth;uniform sampler2D uSurface;uniform sampler2D uHiZ0;uniform sampler2D uHiZ1;uniform sampler2D uHiZ2;uniform sampler2D uHiZ3;uniform sampler2D uHiZ4;uniform int uHiZCount;uniform mat4 uViewProj;uniform mat4 uInvViewProj;uniform vec3 uCameraPos;uniform float uNear;uniform float uFar;uniform float uMaxDistance;uniform float uThickness;uniform float uRoughnessCutoff;uniform int uSteps;uniform int uFrame;
vec3 octDecode(vec2 e){e=e*2.0-1.0;vec3 n=vec3(e,1.0-abs(e.x)-abs(e.y));if(n.z<0.0)n.xy=(1.0-abs(n.yx))*sign(n.xy);return normalize(n);}
vec3 worldAt(vec2 uv,float d){vec4 p=uInvViewProj*vec4(uv*2.0-1.0,d*2.0-1.0,1.0);return p.xyz/p.w;}
float linearize(float d){float z=d*2.0-1.0;return(2.0*uNear*uFar)/max(uFar+uNear-z*(uFar-uNear),1e-6);}
float hash12(vec2 p){vec3 p3=fract(vec3(p.xyx)*.1031);p3+=dot(p3,p3.yzx+33.33);return fract((p3.x+p3.y)*p3.z);}
float hiZ(vec2 uv,int mip){if(uHiZCount<=0)return 1e30;if(mip<=0)return texture(uHiZ0,uv).r;if(mip==1)return texture(uHiZ1,uv).r;if(mip==2)return texture(uHiZ2,uv).r;if(mip==3)return texture(uHiZ3,uv).r;return texture(uHiZ4,uv).r;}
vec3 radiance(vec2 uv,float rough){vec2 t=1.0/vec2(textureSize(uColor,0));float r=rough*rough*3.5;vec3 c=texture(uColor,uv).rgb*2.0;c+=texture(uColor,uv+vec2(t.x*r,0)).rgb;c+=texture(uColor,uv-vec2(t.x*r,0)).rgb;c+=texture(uColor,uv+vec2(0,t.y*r)).rgb;c+=texture(uColor,uv-vec2(0,t.y*r)).rgb;return c/6.0;}
void main(){float d=texture(uDepth,vUv).r;if(d>=.999999){outReflection=vec4(0);return;}vec4 surface=texture(uSurface,vUv);float rough=clamp(surface.b,.045,1.0);if(rough>=uRoughnessCutoff){outReflection=vec4(0);return;}vec3 N=octDecode(surface.rg),P=worldAt(vUv,d),I=normalize(P-uCameraPos),R=reflect(I,N);float NoV=max(dot(N,-I),0.0);if(NoV<.035||dot(R,I)>.98){outReflection=vec4(0);return;}float h0=hash12(gl_FragCoord.xy+float(uFrame)*vec2(17.13,9.71)),h1=hash12(gl_FragCoord.yx+float(uFrame)*vec2(5.37,23.91)),cone=rough*rough*.32,angle=h0*6.2831853,rad=sqrt(h1)*cone;vec3 axis=abs(R.y)<.95?vec3(0,1,0):vec3(1,0,0),T=normalize(cross(axis,R)),B=cross(R,T);R=normalize(R+(cos(angle)*T+sin(angle)*B)*rad);float jitter=.35+.65*hash12(gl_FragCoord.xy+float(uFrame)*31.7);vec2 hitUv=vec2(-1);float hitT=0.0;for(int i=0;i<64;i++){if(i>=uSteps)break;float s=(float(i)+jitter)/float(max(uSteps,1));float t=uMaxDistance*(.12*s+.88*s*s);vec3 Q=P+R*max(t,uThickness*2.0);vec4 clip=uViewProj*vec4(Q,1);if(clip.w<=0.0)break;vec3 ndc=clip.xyz/clip.w;vec2 uv=ndc.xy*.5+.5;if(any(lessThan(uv,vec2(.002)))||any(greaterThan(uv,vec2(.998))))break;float rayDepth=linearize(ndc.z*.5+.5),mipF=clamp(floor(rough*3.0+t/uMaxDistance*2.0),0.0,4.0);int mip=int(mipF);if(uHiZCount>mip&&rayDepth<hiZ(uv,mip)-uThickness*(1.0+rough*2.0))continue;float sceneD=texture(uDepth,uv).r;if(sceneD>=.999999)continue;float sceneDepth=linearize(sceneD),delta=rayDepth-sceneDepth,thick=uThickness*(1.0+t*.025+rough*2.0);if(delta>=0.0&&delta<thick){hitUv=uv;hitT=t;break;}}
if(hitUv.x<0.0){outReflection=vec4(0);return;}float edge=min(min(hitUv.x,hitUv.y),min(1.0-hitUv.x,1.0-hitUv.y));float edgeConfidence=smoothstep(.008,.075,edge),distanceConfidence=1.0-clamp(hitT/uMaxDistance,0.0,1.0),roughConfidence=1.0-smoothstep(uRoughnessCutoff*.55,uRoughnessCutoff,rough),angleConfidence=smoothstep(.035,.3,NoV);float confidence=edgeConfidence*distanceConfidence*roughConfidence*angleConfidence;outReflection=vec4(radiance(hitUv,rough),confidence);}`;
export class ScreenSpaceReflectionPass extends FullscreenPass{texture!:WebGLTexture;framebuffer!:WebGLFramebuffer;width=0;height=0;private hdr=false;constructor(gl:WebGL2RenderingContext,readonly capabilities:RendererCapabilities){super(gl,fs);}ensure(width:number,height:number,hdr:boolean):void{if(this.width===width&&this.height===height&&this.hdr===hdr)return;this.release();const g=this.gl,t=g.createTexture(),f=g.createFramebuffer();if(!t||!f)throw new Error('Failed to allocate SSR target');this.texture=t;this.framebuffer=f;this.width=width;this.height=height;this.hdr=hdr&&this.capabilities.colorBufferFloat;g.bindTexture(g.TEXTURE_2D,t);const filter=!this.hdr||this.capabilities.floatLinearFiltering?g.LINEAR:g.NEAREST;g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,filter);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,filter);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);if(this.hdr)g.texImage2D(g.TEXTURE_2D,0,g.RGBA16F,width,height,0,g.RGBA,g.HALF_FLOAT,null);else g.texImage2D(g.TEXTURE_2D,0,g.RGBA8,width,height,0,g.RGBA,g.UNSIGNED_BYTE,null);g.bindFramebuffer(g.FRAMEBUFFER,f);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,t,0);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw new Error('Incomplete SSR framebuffer');g.bindFramebuffer(g.FRAMEBUFFER,null);g.bindTexture(g.TEXTURE_2D,null);}
 render(color:WebGLTexture,depth:WebGLTexture,surface:WebGLTexture,camera:PbrCameraPacket,depthPyramid:readonly DepthPyramidLevel[],settings:ResolvedScreenSpaceReflectionSettings,frame:number):WebGLTexture{const inv=invertMat4(camera.viewProj);if(!inv)throw new Error('Cannot invert camera matrix for SSR');const g=this.gl;g.bindFramebuffer(g.FRAMEBUFFER,this.framebuffer);g.viewport(0,0,this.width,this.height);g.disable(g.DEPTH_TEST);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);this.program.use();this.bindTexture(0,'uColor',color);this.bindTexture(1,'uDepth',depth);this.bindTexture(2,'uSurface',surface);const levels=depthPyramid.slice(0,5);for(let i=0;i<5;i++)this.bindTexture(4+i,`uHiZ${i}`,levels[i]?.texture??depth);g.uniform1i(this.program.uniform('uHiZCount'),levels.length);g.uniformMatrix4fv(this.program.uniform('uViewProj'),false,camera.viewProj);g.uniformMatrix4fv(this.program.uniform('uInvViewProj'),false,inv);g.uniform3fv(this.program.uniform('uCameraPos'),camera.position);g.uniform1f(this.program.uniform('uNear'),camera.near??.1);g.uniform1f(this.program.uniform('uFar'),camera.far??500);g.uniform1f(this.program.uniform('uMaxDistance'),settings.maxDistance);g.uniform1f(this.program.uniform('uThickness'),settings.thickness);g.uniform1f(this.program.uniform('uRoughnessCutoff'),settings.roughnessCutoff);g.uniform1i(this.program.uniform('uSteps'),settings.steps);g.uniform1i(this.program.uniform('uFrame'),frame&0x7fffffff);this.draw();g.enable(g.DEPTH_TEST);g.bindFramebuffer(g.FRAMEBUFFER,null);return this.texture;}
 private bindTexture(unit:number,name:string,texture:WebGLTexture):void{const g=this.gl;g.activeTexture(g.TEXTURE0+unit);g.bindTexture(g.TEXTURE_2D,texture);g.uniform1i(this.program.uniform(name),unit);}
 private release():void{if(this.texture)this.gl.deleteTexture(this.texture);if(this.framebuffer)this.gl.deleteFramebuffer(this.framebuffer);this.texture=undefined as unknown as WebGLTexture;this.framebuffer=undefined as unknown as WebGLFramebuffer;this.width=this.height=0;this.hdr=false;}
 override dispose():void{this.release();super.dispose();}}
