import type{PbrCameraPacket}from'./PbrPass';import type{LocalLightPacket}from'./Lighting';import{buildLightTiles,type ScreenLight}from'./TiledLights';
export const MAX_LOCAL_LIGHTS=64;export const MAX_LIGHTS_PER_TILE=32;
export interface TiledLightBinding{countsTexture:WebGLTexture;indicesTexture:WebGLTexture;cols:number;rows:number;tileSize:number;lights:readonly LocalLightPacket[];overflow:number;}
export class TiledLightGrid{countsTexture!:WebGLTexture;indicesTexture!:WebGLTexture;private cols=0;private rows=0;private tileSize=16;constructor(readonly gl:WebGL2RenderingContext){}
 update(camera:PbrCameraPacket,lights:readonly LocalLightPacket[],width:number,height:number,tileSize=16):TiledLightBinding{const bounded=lights.slice(0,MAX_LOCAL_LIGHTS);this.ensure(width,height,tileSize);const screen:ScreenLight[]=[];for(let i=0;i<bounded.length;i++){const s=projectLight(camera.viewProj,bounded[i],width,height,i);if(s)screen.push(s);}const built=buildLightTiles(width,height,tileSize,screen,MAX_LIGHTS_PER_TILE),counts=new Uint8Array(this.cols*this.rows),slotsPerTile=MAX_LIGHTS_PER_TILE/4,indices=new Uint8Array(this.cols*slotsPerTile*this.rows*4);indices.fill(255);for(let y=0;y<this.rows;y++)for(let x=0;x<this.cols;x++){const list=built.tiles[y*this.cols+x].indices;counts[y*this.cols+x]=list.length;for(let slot=0;slot<list.length;slot++){const texelX=x*slotsPerTile+Math.floor(slot/4),component=slot&3,offset=(y*this.cols*slotsPerTile+texelX)*4+component;indices[offset]=list[slot];}}const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.countsTexture);g.texSubImage2D(g.TEXTURE_2D,0,0,0,this.cols,this.rows,g.RED_INTEGER,g.UNSIGNED_BYTE,counts);g.bindTexture(g.TEXTURE_2D,this.indicesTexture);g.texSubImage2D(g.TEXTURE_2D,0,0,0,this.cols*slotsPerTile,this.rows,g.RGBA_INTEGER,g.UNSIGNED_BYTE,indices);g.bindTexture(g.TEXTURE_2D,null);return{countsTexture:this.countsTexture,indicesTexture:this.indicesTexture,cols:this.cols,rows:this.rows,tileSize,lights:bounded,overflow:built.overflow+Math.max(0,lights.length-MAX_LOCAL_LIGHTS)};}
 private ensure(width:number,height:number,tileSize:number):void{const cols=Math.ceil(width/tileSize),rows=Math.ceil(height/tileSize);if(cols===this.cols&&rows===this.rows&&tileSize===this.tileSize&&this.countsTexture&&this.indicesTexture)return;this.dispose();this.cols=cols;this.rows=rows;this.tileSize=tileSize;const g=this.gl,c=g.createTexture(),i=g.createTexture();if(!c||!i)throw new Error('Failed to allocate tiled light textures');this.countsTexture=c;this.indicesTexture=i;g.bindTexture(g.TEXTURE_2D,c);setIntegerTextureParams(g);g.texImage2D(g.TEXTURE_2D,0,g.R8UI,cols,rows,0,g.RED_INTEGER,g.UNSIGNED_BYTE,null);g.bindTexture(g.TEXTURE_2D,i);setIntegerTextureParams(g);g.texImage2D(g.TEXTURE_2D,0,g.RGBA8UI,cols*(MAX_LIGHTS_PER_TILE/4),rows,0,g.RGBA_INTEGER,g.UNSIGNED_BYTE,null);g.bindTexture(g.TEXTURE_2D,null);}
 dispose():void{if(this.countsTexture)this.gl.deleteTexture(this.countsTexture);if(this.indicesTexture)this.gl.deleteTexture(this.indicesTexture);this.countsTexture=undefined as unknown as WebGLTexture;this.indicesTexture=undefined as unknown as WebGLTexture;this.cols=this.rows=0;}
}
function setIntegerTextureParams(g:WebGL2RenderingContext){g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);}
function projectLight(m:Float32Array,l:LocalLightPacket,width:number,height:number,index:number):ScreenLight|undefined{const c=project(m,l.position,width,height);if(!c||c.w<=0)return;let radius=0;const p=l.position;for(const axis of [[l.range,0,0],[0,l.range,0],[0,0,l.range]] as [number,number,number][]){const q:[number,number,number]=[p[0]+axis[0],p[1]+axis[1],p[2]+axis[2]],s=project(m,q,width,height);if(s)radius=Math.max(radius,Math.hypot(s.x-c.x,s.y-c.y));}if(radius<=.5)return;return{x:c.x,y:c.y,radius,depthMin:Math.max(-1,c.z-.2),depthMax:Math.min(1,c.z+.2),index};}
function project(m:Float32Array,p:[number,number,number],width:number,height:number):{x:number;y:number;z:number;w:number}|undefined{const x=p[0],y=p[1],z=p[2],cx=m[0]*x+m[4]*y+m[8]*z+m[12],cy=m[1]*x+m[5]*y+m[9]*z+m[13],cz=m[2]*x+m[6]*y+m[10]*z+m[14],w=m[3]*x+m[7]*y+m[11]*z+m[15];if(Math.abs(w)<1e-6)return;return{x:(cx/w*.5+.5)*width,y:(cy/w*.5+.5)*height,z:cz/w,w};}
